version: '3.8'

services:
  web:
    build: .
    ports:
      - ${API_PORT_EXTERNAL}:${API_PORT_INTERNAL}
    environment:
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      PGHOST: ${POSTGRES_HOST}
      PGPORT: ${POSTGRES_PORT}
<<<<<<< HEAD
      LOADERIO: ${LOADERIO}
=======
>>>>>>> 33d5cced7ebfde8f0dd03de7d0e9cfc492bb17d0
